server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: gdlq11
    url: jdbc:mysql://112.74.59.110:3306/test?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

  # thymeleaf
    thymeleaf:
    # 关闭缓存
        cache: false



mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml